# This workflow will install Python dependencies, run unit tests, lint, format, build the image, run integration
# tests, and then push the image to my private Docker repo with a single version of Python.
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black pytest
        if [ -f task_3/requirements/runtime.txt ]; then pip install -r task_3/requirements/runtime.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Format with black
      run: |
        # Checks if all files in the current directory are Black-formatted
        black . --check --diff --color
    - name: unit tests
      run: |
        pytest ./task_3/tests/test_features.py
        pytest ./task_3/tests/test_preprocessing.py

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Start services (download db then run db and ) with docker-compose (CI)
      working-directory: ./task_3
      env:
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: docker compose -f docker-compose.yaml -f docker-compose.ci.yaml up -d --build



    - name: Run integration tests
      working-directory: ./task_3
      env:
        DB_CONNECTION_STRING: postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/olist-db
      run: |
        pytest ./tests/test_integration_notebook_parity.py
        pytest ./tests/test_integration_API_endpoints.py
        pytest ./tests/test_integration_pipeline
        docker rm -f test-container

    - name: Tear down services
      if: always()
      working-directory: ./task_3
      run: docker compose -f docker-compose.yaml -f docker-compose.ci.yaml down -v



    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push image to my private docker repo
      uses: docker/build-push-action@v6
      with:
        context: ./task_3
        push: true
        tags: youssef375/olistai-is_late_app:latest

